vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        produits_image:
            uri_prefix: /images/photoProduits
            upload_destination: '%kernel.project_dir%/public/images/photoProduits'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
        utilisateurs_image:
            uri_prefix: /images/photoUsers
            upload_destination: '%kernel.project_dir%/public/images/photoUsers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 
        batiments_image:
            uri_prefix: /images/photoBatiments
            upload_destination: '%kernel.project_dir%/public/images/photoBatiments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 
        ambulances_image:
            uri_prefix: /images/photoAmbulances
            upload_destination: '%kernel.project_dir%/public/images/photoAmbulances'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 
        marques_image:
            uri_prefix: /images/photoMarques
            upload_destination: '%kernel.project_dir%/public/images/photoMarques'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 
        fichiers_examens:
            uri_prefix: /fichiersExamens
            upload_destination: '%kernel.project_dir%/public/fichiersExamens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 



